elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
  log_opt:
    max-size: "100m"
  log_driver: "json-file"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000/udp"
  links:
    - elasticsearch
  log_opt:
    max-size: "100m"
  log_driver: "json-file"

kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  log_opt:
    max-size: "100m"
  log_driver: "json-file"
